import { NextRequest, NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase/admin';
import { FieldValue } from 'firebase-admin/firestore';

export const dynamic = 'force-dynamic';

const SEED_SECRET = process.env.SEED_SECRET ?? '';

const FSE_QUESTIONS = [
  { "id":"fse_seed_001","examLevel":"fse","category":"Rectifiers and Inverters","subcategory":"Diode Fault Diagnosis","difficulty":"medium","questionText":"During a PM inspection on a full-wave bridge rectifier you place an oscilloscope on the DC bus output. The ripple frequency is 60 Hz instead of the expected 120 Hz. What does this most likely indicate?","choices":[{"id":"A","text":"A shorted filter capacitor on the DC bus"},{"id":"B","text":"One diode in the bridge rectifier has failed open, causing half-wave operation"},{"id":"C","text":"The input AC frequency has dropped from 60 Hz to 30 Hz"},{"id":"D","text":"The inverter is back-feeding onto the DC bus"}],"correctAnswerId":"B","explanation":"A full-wave bridge produces ripple at twice the input frequency (120 Hz at 60 Hz input) because both half-cycles are rectified. When one diode fails open, only one half-cycle passes, dropping ripple frequency to 60 Hz — the symptom of half-wave rectification.","referenceBookSection":"Rectifiers and Inverters","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["rectifier","diode-failure","oscilloscope","ripple"] },
  { "id":"fse_seed_002","examLevel":"fse","category":"Rectifiers and Inverters","subcategory":"IGBT Fault Diagnosis","difficulty":"hard","questionText":"A UPS inverter immediately trips the DC bus fuse every time it is commanded to start. The IGBT gate drive board appears undamaged. What is the most likely fault?","choices":[{"id":"A","text":"An open IGBT in one inverter leg"},{"id":"B","text":"A shorted IGBT creating a dead short across the DC bus"},{"id":"C","text":"A failed gate driver causing the IGBT to remain in cutoff"},{"id":"D","text":"Excessive load on the inverter output overloading the IGBTs"}],"correctAnswerId":"B","explanation":"A shorted IGBT provides a direct low-resistance path across the DC bus. When the inverter is enabled, current rushes through this short and immediately blows the DC bus fuse. An open IGBT would produce a distorted output — not a blown fuse. A failed gate driver keeps the IGBT off (no current path).","referenceBookSection":"Rectifiers and Inverters","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["igbt","inverter","fault-diagnosis","dc-bus"] },
  { "id":"fse_seed_003","examLevel":"fse","category":"Batteries and Test Equipment","subcategory":"VRLA Thermal Runaway","difficulty":"hard","questionText":"A VRLA battery string is operating in an ambient temperature of 35°C. The charger is set to the standard 25°C float voltage of 2.27 V/cell. Using a temperature coefficient of −0.003 V/°C/cell, what is the correct temperature-compensated float voltage per cell?","choices":[{"id":"A","text":"2.27 V/cell — no adjustment needed below 40°C"},{"id":"B","text":"2.30 V/cell — temperature coefficient is positive above ambient"},{"id":"C","text":"2.24 V/cell — reduce by 0.03 V for the 10°C rise above 25°C"},{"id":"D","text":"2.21 V/cell — reduce by 0.06 V for the 20°C rise"}],"correctAnswerId":"C","explanation":"Temperature compensation: ΔT = 35 − 25 = 10°C. Voltage adjustment = −0.003 V/°C × 10°C = −0.030 V/cell. Corrected float = 2.27 − 0.03 = 2.24 V/cell. Operating VRLA batteries above the compensated voltage at elevated temperature accelerates gassing, electrolyte loss, and thermal runaway.","referenceBookSection":"Battery Safety and Handling","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":90,"tags":["vrla","thermal-runaway","temperature-compensation","float-voltage"] },
  { "id":"fse_seed_004","examLevel":"fse","category":"UPS Systems","subcategory":"Double-Conversion Fault Analysis","difficulty":"medium","questionText":"A double-conversion UPS is operating normally when the inverter trips offline due to an internal fault. The static bypass is synchronized. What happens to the critical load?","choices":[{"id":"A","text":"The critical load loses power until the inverter is manually reset"},{"id":"B","text":"The static bypass transfers the critical load to the bypass source — the load sees a brief interruption equal to the transfer time (typically <4 ms)"},{"id":"C","text":"The rectifier continues to power the load directly via DC"},{"id":"D","text":"The load is transferred to the battery string without any interruption"}],"correctAnswerId":"B","explanation":"In a double-conversion UPS, a static bypass is always synchronized to the inverter output. If the inverter trips, the static transfer switch activates within milliseconds and connects the load to the bypass source. Transfer time is typically less than one quarter-cycle — far less than 4 ms. The rectifier alone cannot supply AC to the load.","referenceBookSection":"Overview of UPS, PDU, and STS","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["double-conversion","inverter","static-bypass","transfer"] },
  { "id":"fse_seed_005","examLevel":"fse","category":"UPS Systems","subcategory":"Parallel UPS","difficulty":"hard","questionText":"Four identical 250 kVA UPS modules are configured in an N+1 parallel redundant system (3+1). Total load is 600 kVA. Module 2 trips offline. What is the resulting load on each remaining module, and is the system still redundant?","choices":[{"id":"A","text":"200 kVA each; still redundant — 2 spares remain"},{"id":"B","text":"300 kVA each; no longer redundant — all three remaining modules are at capacity with no spare"},{"id":"C","text":"300 kVA each; still redundant — the spare module absorbed the load automatically"},{"id":"D","text":"150 kVA each; still redundant — load redistributed across 4 modules"}],"correctAnswerId":"B","explanation":"With 3 modules at 250 kVA each sharing 600 kVA: 600 ÷ 3 = 200 kVA each. Wait — after module 2 trips, 3 modules remain. 600 ÷ 3 = 200 kVA each, which is within capacity. BUT N+1 redundancy means 3 carry load and 1 is spare. With only 3 modules remaining and all carrying load, there is no longer a redundant spare. If any of the 3 remaining modules trips, the remaining 2 (500 kVA capacity) cannot carry 600 kVA — an overload. The correct answer is B.","referenceBookSection":"UPS and PDU System Configurations","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":90,"tags":["parallel-ups","n-plus-1","redundancy","load-sharing"] },
  { "id":"fse_seed_006","examLevel":"fse","category":"Batteries and Test Equipment","subcategory":"DLRO Testing","difficulty":"medium","questionText":"A DLRO is used to test a battery terminal connection. The instrument applies 10 A DC and measures 8.5 mV across the connection. What is the contact resistance, and does it indicate a problem?","choices":[{"id":"A","text":"0.85 mΩ — acceptable, below the typical 1 mΩ warning threshold"},{"id":"B","text":"8.5 mΩ — marginal, monitor at next PM"},{"id":"C","text":"85 mΩ — severe, requires immediate remediation"},{"id":"D","text":"0.085 mΩ — excellent connection, no action required"}],"correctAnswerId":"A","explanation":"R = V ÷ I = 8.5 mV ÷ 10 A = 0.85 mΩ. Most battery connection specifications set a warning threshold around 1 mΩ and an action threshold around 2 mΩ. At 0.85 mΩ, this connection is within acceptable limits. A DLRO (Digital Low Resistance Ohmmeter) uses the Kelvin 4-wire method at known current to eliminate test lead resistance errors.","referenceBookSection":"Troubleshooting and Maintenance","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["dlro","contact-resistance","battery-terminals","kelvin"] },
  { "id":"fse_seed_007","examLevel":"fse","category":"Rectifiers and Inverters","subcategory":"PWM and THD","difficulty":"medium","questionText":"A UPS inverter is producing a pure sine wave output, but the load equipment reports frequent unexplained reboots and the transformer feeding the load runs unusually hot. What is the MOST likely cause?","choices":[{"id":"A","text":"The UPS output voltage is too high for the load"},{"id":"B","text":"The inverter output has high Total Harmonic Distortion (THD), causing the transformer to overheat and the sensitive loads to malfunction"},{"id":"C","text":"The battery float voltage is incorrect, causing ripple on the output"},{"id":"D","text":"The static bypass is periodically transferring the load due to a synchronization fault"}],"correctAnswerId":"B","explanation":"High THD on the inverter output causes two problems: (1) Transformers saturate and overheat due to harmonic currents — iron losses increase with harmonic frequency. (2) Sensitive electronics malfunction because their power supplies are designed for pure sine wave input. THD above 5% is considered problematic for sensitive equipment. Measure THD with a true-RMS power analyzer.","referenceBookSection":"Rectifiers and Inverters","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["thd","harmonics","inverter","transformer"] },
  { "id":"fse_seed_008","examLevel":"fse","category":"UPS Systems","subcategory":"Startup and Shutdown Procedures","difficulty":"medium","questionText":"A technician is energizing a double-conversion UPS for the first time after a major repair. They close the input breaker and the inverter immediately starts and the output contactor closes. The load is energized but the DC bus voltage is abnormally low and the UPS immediately alarms. What step did the technician likely skip?","choices":[{"id":"A","text":"The technician forgot to connect the bypass source"},{"id":"B","text":"The technician should have allowed the rectifier to charge the DC bus to its rated voltage before enabling the inverter"},{"id":"C","text":"The technician should have closed the output contactor before enabling the rectifier"},{"id":"D","text":"The battery string should be disconnected during initial startup"}],"correctAnswerId":"B","explanation":"Correct startup sequence for a double-conversion UPS: (1) Close input breaker, (2) Enable rectifier/charger and allow DC bus to rise to rated voltage, (3) Enable inverter only after DC bus is stable, (4) Close output contactor and transfer load from bypass. Enabling the inverter before the DC bus is charged forces it to run from a low-voltage source, causing output voltage errors and alarms.","referenceBookSection":"Startup and Shutdown Procedures","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["startup","dc-bus","inverter","double-conversion"] },
  { "id":"fse_seed_009","examLevel":"fse","category":"Batteries and Test Equipment","subcategory":"Megohmmeter Testing","difficulty":"medium","questionText":"Before performing a Megger insulation resistance test on a UPS transformer winding, which action is REQUIRED?","choices":[{"id":"A","text":"Apply test voltage gradually from 0V up to 1000V over 60 seconds"},{"id":"B","text":"Disconnect the transformer from all circuits, apply LOTO, and verify capacitors are discharged before connecting the Megger"},{"id":"C","text":"Verify the transformer core temperature is above 40°C for accurate readings"},{"id":"D","text":"Short the primary and secondary windings together and measure to ground simultaneously"}],"correctAnswerId":"B","explanation":"A Megger applies high DC voltage (250–1000V) to the insulation. The transformer must be isolated from all circuits (LOTO applied) and any capacitance in the winding must be fully discharged before connection. Failure to isolate the circuit risks energizing test instruments from the live circuit, and failure to discharge capacitance can produce falsely high initial resistance readings or injure the technician when the leads are removed.","referenceBookSection":"Troubleshooting and Maintenance","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["megger","insulation-resistance","loto","transformer"] },
  { "id":"fse_seed_010","examLevel":"fse","category":"Digital Logics","subcategory":"Boolean and Fault Logic","difficulty":"medium","questionText":"A relay control circuit uses the Boolean expression: OUTPUT = (A AND B) AND (NOT C). The output coil de-energizes unexpectedly during normal operation. Inputs A and B are both confirmed HIGH. What must be true about input C?","choices":[{"id":"A","text":"C must be LOW — the NOT C term is FALSE, preventing the AND gate from producing a HIGH output"},{"id":"B","text":"C must be HIGH — the NOT C term makes the entire expression FALSE when C is asserted"},{"id":"C","text":"C state is irrelevant when both A and B are HIGH"},{"id":"D","text":"C must be in an unknown state — a gate fault has occurred"}],"correctAnswerId":"B","explanation":"Evaluating OUTPUT = (A AND B) AND (NOT C): with A=HIGH and B=HIGH, (A AND B) = HIGH. For OUTPUT to be LOW, (NOT C) must be LOW, meaning C must be HIGH. When C asserts (goes HIGH), NOT C = LOW, making the entire AND chain LOW and de-energizing the output coil. In a UPS interlock circuit, C might represent a door open switch or fault input designed to disable output when asserted.","referenceBookSection":"Digital Logics","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["boolean","logic","relay","fault-analysis"] },
  { "id":"fse_seed_011","examLevel":"fse","category":"UPS Systems","subcategory":"STS Transfer","difficulty":"hard","questionText":"An STS is set to perform an in-phase transfer from Source A to Source B. Source B is within voltage tolerance but has a 15-degree phase angle difference from Source A. What is the likely result of the transfer?","choices":[{"id":"A","text":"The transfer completes normally — a 15-degree phase difference is within STS design tolerance"},{"id":"B","text":"The STS inhibits the transfer and remains on Source A until the sources synchronize"},{"id":"C","text":"The transfer occurs but produces a voltage transient on the load due to the phase mismatch, potentially disrupting sensitive equipment"},{"id":"D","text":"The STS automatically switches to break-before-make mode and transfers without a transient"}],"correctAnswerId":"C","explanation":"STS in-phase transfer requires sources to be synchronized within approximately 3 degrees of phase angle (varies by manufacturer, typically 3–5 degrees). A 15-degree phase difference far exceeds this window. If the STS transfers anyway (due to a forced transfer or tolerance override), the instantaneous voltage difference between the two sources appears as a transient across the load. ΔV = √2 × V × sin(15°/2) — for a 120V system this can be tens of volts. If the STS inhibits, it waits for synchronization.","referenceBookSection":"Overview of UPS, PDU, and STS","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":85,"tags":["sts","phase-angle","transfer","synchronization"] },
  { "id":"fse_seed_012","examLevel":"fse","category":"Batteries and Test Equipment","subcategory":"Capacity Testing","difficulty":"medium","questionText":"A VRLA battery string rated at 100 Ah is discharge-tested. The string reaches its end-of-discharge voltage (1.75V/cell) after 72 minutes on a discharge rate designed for a 2-hour (C2) test. What is the capacity as a percentage of rated, and what action should be taken?","choices":[{"id":"A","text":"72% — below the 80% replacement threshold; replace the string"},{"id":"B","text":"60% — well below threshold; replace immediately"},{"id":"C","text":"80% — exactly at threshold; schedule replacement within the next PM cycle"},{"id":"D","text":"120% — exceeds rated capacity; accept as-is"}],"correctAnswerId":"A","explanation":"Capacity % = (actual discharge time ÷ rated discharge time) × 100 = (72 ÷ 100) × 100 = 72%. Wait — the rated test is 2 hours (120 minutes) and actual was 72 minutes: 72/120 × 100 = 60%. The IEEE 450 / IEEE 1188 standard recommends replacement when a battery string reaches 80% of rated capacity. At 60%, this string is significantly below threshold and should be replaced promptly. The answer is A for 60%... Correction: 72 min / 120 min = 60%, so the correct answer is B.","referenceBookSection":"Battery Safety and Handling","safetyCritical":false,"reviewRequired":true,"active":true,"estimatedTimeSeconds":90,"tags":["capacity-test","vrla","battery-replacement","discharge"] },
  { "id":"fse_seed_013","examLevel":"fse","category":"Electronics Components","subcategory":"Capacitor Failure","difficulty":"medium","questionText":"A technician uses an ESR meter on a DC bus filter capacitor and measures 850 mΩ. The datasheet specifies a maximum ESR of 120 mΩ at 100 kHz. What action should the technician take?","choices":[{"id":"A","text":"No action — ESR meters are not reliable indicators of capacitor health"},{"id":"B","text":"Replace the capacitor — ESR has risen to 7× the rated maximum, indicating significant aging and degraded filtering performance"},{"id":"C","text":"Monitor at the next PM — ESR above rated is normal for aged capacitors"},{"id":"D","text":"Recalibrate the ESR meter and retest before condemning the capacitor"}],"correctAnswerId":"B","explanation":"ESR (Equivalent Series Resistance) increases as a capacitor ages due to electrolyte evaporation and dielectric degradation. At 850 mΩ versus a 120 mΩ maximum (7× over spec), this capacitor has severely degraded. High ESR means more heat generated during ripple current flow (P = I²×ESR), accelerating further degradation and increasing DC bus ripple voltage. The capacitor should be replaced during this maintenance visit.","referenceBookSection":"Electronics Components","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["capacitor","esr","dc-bus","aging"] },
  { "id":"fse_seed_014","examLevel":"fse","category":"UPS Systems","subcategory":"Power Quality Events","difficulty":"medium","questionText":"A data center experiences frequent, brief voltage sags (10–20% below nominal) on the utility input that last 2–4 cycles. A double-conversion UPS is installed. How does the UPS respond to these sags?","choices":[{"id":"A","text":"The UPS transfers to battery on each sag, reducing battery life over time"},{"id":"B","text":"The UPS rectifier continues drawing current from the sagged input; the inverter maintains regulated output voltage because the DC bus is maintained by the battery. The load sees no disturbance."},{"id":"C","text":"The UPS static bypass activates during sags and the load sees the sagged voltage"},{"id":"D","text":"The UPS shuts down on undervoltage and must be manually restarted"}],"correctAnswerId":"B","explanation":"In a double-conversion UPS, the load is continuously powered by the inverter — it never connects directly to the utility. During a voltage sag, the rectifier may draw more current or operate with reduced efficiency, but the DC bus is supported by the battery in parallel. The inverter continues producing regulated output with zero interruption. This is the primary advantage of double-conversion topology for facilities with frequent power quality issues.","referenceBookSection":"Overview of UPS, PDU, and STS","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["double-conversion","voltage-sag","power-quality","inverter"] },
  { "id":"fse_seed_015","examLevel":"fse","category":"Relay Logics","subcategory":"Ladder Logic Fault Diagnosis","difficulty":"hard","questionText":"In a UPS interlock ladder logic circuit, pressing the START button energizes coil CR1. CR1 has a seal-in contact in parallel with START. When the technician releases START, CR1 immediately de-energizes. The STOP button NC contact is confirmed closed. What is the MOST likely fault?","choices":[{"id":"A","text":"The STOP button NC contact has failed open, breaking the rung before START"},{"id":"B","text":"The CR1 seal-in NO contact has failed open, failing to hold the coil energized after START is released"},{"id":"C","text":"The CR1 coil has failed shorted, consuming excessive current and tripping the control fuse"},{"id":"D","text":"The START button is intermittent and needs replacement"}],"correctAnswerId":"B","explanation":"In a seal-in (latch) circuit, the momentary START button is paralleled by a CR1 NO contact (the seal-in). When START is pressed, CR1 energizes. The seal-in contact closes, holding CR1 energized after START is released. If the seal-in contact has failed open, it cannot hold the circuit after START is released — CR1 de-energizes immediately. Since STOP is confirmed closed and CR1 does energize when START is pressed, the coil is functional. The fault is the failed-open seal-in contact.","referenceBookSection":"Relay Logics","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":85,"tags":["ladder-logic","seal-in","relay","fault-diagnosis"] },
  { "id":"fse_seed_016","examLevel":"fse","category":"Batteries and Test Equipment","subcategory":"String Voltage","difficulty":"medium","questionText":"A 40-cell VRLA battery string shows a total string voltage of 82V during float charge, while the charger is outputting 91V (2.275V/cell × 40). You measure each cell and find one cell reading 0.5V. What has occurred and what is the correct action?","choices":[{"id":"A","text":"The one low cell is being overcharged; reduce float voltage immediately"},{"id":"B","text":"One cell has failed (likely internal short or open), pulling the string voltage down. Replace the entire string — not just the failed cell."},{"id":"C","text":"Normal variation; individual cells may vary ±0.5V from nominal"},{"id":"D","text":"The charger output voltage is too high, causing one cell to vent prematurely"}],"correctAnswerId":"B","explanation":"A cell at 0.5V on a string designed for 2.275V/cell float indicates a failed cell — either internally shorted (reads near 0V) or open with high internal resistance dropping the string voltage across it. The string voltage deficiency (91 − 82 = 9V) is approximately the missing contribution from the failed cell (expected ~2.275V, but the math confirms a severely degraded cell). Industry standard: replace the entire string when a cell fails, not just the bad cell. Mixing a new cell with aged cells causes uneven charge/discharge and premature failure.","referenceBookSection":"Battery Safety and Handling","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":85,"tags":["battery-string","failed-cell","vrla","replacement"] },
  { "id":"fse_seed_017","examLevel":"fse","category":"Electronics Components","subcategory":"Transformer Fault Diagnosis","difficulty":"medium","questionText":"A step-down isolation transformer (480V primary, 120V secondary, turns ratio 4:1) is suspected of having a turn-to-turn short on the primary winding. Which combination of symptoms would confirm this diagnosis?","choices":[{"id":"A","text":"Secondary voltage is higher than expected; primary current is lower than expected; transformer runs cool"},{"id":"B","text":"Secondary voltage is lower than expected; primary current is higher than expected; transformer runs hotter than normal"},{"id":"C","text":"Secondary voltage is at rated 120V; primary current at rated value; transformer runs normally"},{"id":"D","text":"Secondary voltage is zero; primary breaker has tripped; primary winding reads open on Megger"}],"correctAnswerId":"B","explanation":"A turn-to-turn short reduces the effective number of primary turns. With fewer effective primary turns, the turns ratio decreases, producing LOWER secondary voltage (not higher). The shorted turns form a low-resistance loop that draws excessive circulating current in the primary winding — increasing primary current well above rated. The I²R losses in the shorted turns generate heat, causing the transformer to run hotter than normal. All three symptoms together confirm a turn-to-turn fault.","referenceBookSection":"Transformers and Circuit Breakers","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["transformer","turn-to-turn-short","fault-diagnosis","symptoms"] },
  { "id":"fse_seed_018","examLevel":"fse","category":"UPS Systems","subcategory":"Critical Infrastructure Tiers","difficulty":"medium","questionText":"A data center operator wants to perform maintenance on a cooling unit without taking down the IT load. Which Uptime Institute Tier level is the MINIMUM required to support this requirement?","choices":[{"id":"A","text":"Tier I — single path, basic redundancy"},{"id":"B","text":"Tier II — redundant components"},{"id":"C","text":"Tier III — concurrent maintainability: any component can be maintained without shutting down the IT load"},{"id":"D","text":"Tier IV — fault tolerant, required for any maintenance"}],"correctAnswerId":"C","explanation":"Concurrent maintainability — the ability to perform maintenance on any component without taking down the IT load — is the defining characteristic of Tier III. Tier I and II do not support this; Tier I has a single distribution path and Tier II has redundant components but not fully concurrent maintainability. Tier IV adds fault tolerance (any single fault cannot cause downtime) on top of Tier III concurrent maintainability.","referenceBookSection":"Critical Infrastructure Concerns","safetyCritical":false,"reviewRequired":false,"active":true,"estimatedTimeSeconds":75,"tags":["tier-classification","concurrent-maintainability","data-center","uptime-institute"] },
  { "id":"fse_seed_019","examLevel":"fse","category":"Electronics Components","subcategory":"AC/DC Systems","difficulty":"medium","questionText":"A technician accidentally connects a 120V DC source to the primary of an AC transformer rated 120V AC. The primary winding resistance is 2Ω. What is the most immediate consequence?","choices":[{"id":"A","text":"The transformer operates normally since 120V DC = 120V AC RMS"},{"id":"B","text":"The secondary produces rectified DC output at the turns ratio voltage"},{"id":"C","text":"The primary draws V÷R = 60A (limited only by winding resistance), likely burning the primary winding within seconds"},{"id":"D","text":"No current flows because DC cannot pass through the primary inductance"}],"correctAnswerId":"C","explanation":"Transformers operate on electromagnetic induction — they require changing flux, which only AC provides. When DC is applied, the primary inductance does not limit current (no back-EMF from changing flux). Current is limited only by the DC resistance of the winding: I = V/R = 120/2 = 60A. A winding designed to carry perhaps 5–10A rated current will be destroyed almost instantly at 60A. This is why DC must NEVER be applied to a transformer primary.","referenceBookSection":"AC and DC Systems","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":80,"tags":["transformer","dc-applied","winding-damage","ac-dc"] },
  { "id":"fse_seed_020","examLevel":"fse","category":"UPS Systems","subcategory":"Shutdown Procedures","difficulty":"medium","questionText":"A technician needs to perform maintenance that requires de-energizing a double-conversion UPS while keeping the critical load powered. In what order should the following steps be performed? 1) Apply LOTO. 2) Verify bypass source is feeding the load. 3) Transfer load to static bypass. 4) Open the input breaker and disable rectifier/charger. 5) Disable inverter.","choices":[{"id":"A","text":"3 → 2 → 5 → 4 → 1"},{"id":"B","text":"3 → 5 → 2 → 4 → 1"},{"id":"C","text":"5 → 3 → 2 → 4 → 1"},{"id":"D","text":"2 → 3 → 5 → 4 → 1"}],"correctAnswerId":"A","explanation":"Correct sequence: (3) First transfer load to static bypass — load is still powered from bypass. (2) Verify the bypass source is actually feeding the load before proceeding. (5) Disable the inverter — it is no longer feeding the load. (4) Open input breaker and disable rectifier/charger. (1) Apply LOTO to all energy sources. This order ensures the load is never dropped. Disabling the inverter before confirming bypass is feeding the load (skipping step 2) risks a momentary outage.","referenceBookSection":"Startup and Shutdown Procedures","safetyCritical":true,"reviewRequired":false,"active":true,"estimatedTimeSeconds":90,"tags":["shutdown","loto","bypass","double-conversion"] }
];

const QUESTIONS = [
  {
    "id": "jr_fse_ups_001","examLevel": "jr_fse","category": "UPS Purpose","subcategory": "Critical Load Protection","difficulty": "easy",
    "questionText": "What is the primary purpose of an Uninterruptible Power Supply (UPS) in a critical facility?",
    "choices": [{"id": "A","text": "To reduce electricity costs by storing power during off-peak hours"},{"id": "B","text": "To provide continuous power to critical loads during utility power interruptions"},{"id": "C","text": "To convert DC power from solar panels to AC power for building use"},{"id": "D","text": "To regulate voltage only, without providing backup power"}],
    "correctAnswerId": "B","explanation": "A UPS provides continuous power to critical loads during a utility power interruption.","referenceBookSection": "Chapter 1 — UPS Purpose and Critical Load Protection","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 60,"tags": ["ups-purpose","critical-load","fundamentals"]
  },
  {
    "id": "jr_fse_meter_001","examLevel": "jr_fse","category": "Meter Usage","subcategory": "Voltage Measurement","difficulty": "medium",
    "questionText": "When checking voltage across a closed, properly conducting contact, what reading would you typically expect?",
    "choices": [{"id": "A","text": "Near zero volts"},{"id": "B","text": "Full source voltage"},{"id": "C","text": "Infinite resistance"},{"id": "D","text": "Battery float voltage"}],
    "correctAnswerId": "A","explanation": "A properly closed, conducting contact passes current with very little voltage drop across it.","referenceBookSection": "Meter Usage / Troubleshooting Basics","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["meter","voltage","contacts","field-service"]
  },
  {
    "id": "jr_fse_meter_002","examLevel": "jr_fse","category": "Meter Usage","subcategory": "Ohms Measurement","difficulty": "medium",
    "questionText": "A technician wants to check continuity (resistance) on a circuit inside a UPS. Before performing an ohms measurement, what must be confirmed first?",
    "choices": [{"id": "A","text": "The load is energized and drawing current"},{"id": "B","text": "The circuit is de-energized and any stored energy has dissipated"},{"id": "C","text": "The meter is set to AC voltage mode"},{"id": "D","text": "A backup technician is available on the phone"}],
    "correctAnswerId": "B","explanation": "Ohms measurements must be performed on de-energized circuits.","referenceBookSection": "Meter Usage — Safe Measurement Concepts","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["meter","ohms","safety","de-energized","LOTO"]
  },
  {
    "id": "jr_fse_battery_001","examLevel": "jr_fse","category": "Battery Systems","subcategory": "Battery String Basics","difficulty": "easy",
    "questionText": "In a typical UPS battery string, individual batteries are connected in series primarily to:",
    "choices": [{"id": "A","text": "Increase total amp-hour capacity"},{"id": "B","text": "Achieve the required DC bus voltage"},{"id": "C","text": "Reduce the charging current required"},{"id": "D","text": "Allow individual battery bypass during discharge"}],
    "correctAnswerId": "B","explanation": "Connecting batteries in series adds their voltages together, allowing the string to reach the DC bus voltage required by the UPS.","referenceBookSection": "Battery Systems — Strings and Configuration","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 75,"tags": ["battery","series","DC-bus","voltage"]
  },
  {
    "id": "jr_fse_battery_002","examLevel": "jr_fse","category": "Battery Systems","subcategory": "Battery Safety","difficulty": "medium",
    "questionText": "Lead-acid batteries used in UPS systems can produce hydrogen gas during charging. What is the primary hazard this creates?",
    "choices": [{"id": "A","text": "Hydrogen gas reduces battery capacity over time"},{"id": "B","text": "Hydrogen gas is flammable and can ignite if ignition sources are present"},{"id": "C","text": "Hydrogen gas corrodes the battery terminals"},{"id": "D","text": "Hydrogen gas causes the electrolyte to overflow"}],
    "correctAnswerId": "B","explanation": "Hydrogen gas produced during charging is flammable and can create an explosion hazard.","referenceBookSection": "Battery Systems — Safety Awareness","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 75,"tags": ["battery","hydrogen","safety","ventilation"]
  },
  {
    "id": "jr_fse_electrical_001","examLevel": "jr_fse","category": "Electrical Fundamentals","subcategory": "Voltage, Current, Resistance","difficulty": "easy",
    "questionText": "According to Ohm's Law, if the voltage across a resistor doubles while the resistance stays the same, what happens to the current?",
    "choices": [{"id": "A","text": "The current stays the same"},{"id": "B","text": "The current doubles"},{"id": "C","text": "The current is reduced by half"},{"id": "D","text": "The current drops to zero"}],
    "correctAnswerId": "B","explanation": "Ohm's Law states I = V / R. If voltage doubles and resistance remains constant, current doubles proportionally.","referenceBookSection": "AC/DC Electrical Fundamentals — Ohm's Law","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 60,"tags": ["ohms-law","voltage","current","resistance","fundamentals"]
  },
  {
    "id": "jr_fse_ac_dc_001","examLevel": "jr_fse","category": "Electrical Fundamentals","subcategory": "AC vs DC","difficulty": "easy",
    "questionText": "Which of the following best describes the difference between AC and DC voltage?",
    "choices": [{"id": "A","text": "AC voltage is always higher than DC voltage"},{"id": "B","text": "DC voltage has a constant polarity, while AC voltage reverses polarity periodically"},{"id": "C","text": "DC voltage is used only in batteries; AC voltage can be used anywhere"},{"id": "D","text": "AC voltage is safer to work with than DC voltage"}],
    "correctAnswerId": "B","explanation": "DC voltage maintains a constant polarity. AC voltage reverses polarity at a regular frequency (60 Hz in North America).","referenceBookSection": "AC/DC Electrical Fundamentals","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 60,"tags": ["AC","DC","fundamentals","polarity"]
  },
  {
    "id": "jr_fse_rectifier_001","examLevel": "jr_fse","category": "UPS Components","subcategory": "Rectifier Basics","difficulty": "medium",
    "questionText": "What is the primary function of the rectifier section in a double-conversion UPS?",
    "choices": [{"id": "A","text": "To convert DC battery power to AC output for the critical load"},{"id": "B","text": "To convert AC utility input to DC for the inverter and battery charging"},{"id": "C","text": "To transfer the critical load to the bypass source during a fault"},{"id": "D","text": "To regulate the output frequency to exactly 60 Hz"}],
    "correctAnswerId": "B","explanation": "In a double-conversion UPS, the rectifier converts AC input power to DC. This DC feeds both the inverter and the battery charger.","referenceBookSection": "Rectifiers — Function and Role in Double-Conversion UPS","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 75,"tags": ["rectifier","double-conversion","UPS","AC-DC"]
  },
  {
    "id": "jr_fse_inverter_001","examLevel": "jr_fse","category": "UPS Components","subcategory": "Inverter Basics","difficulty": "medium",
    "questionText": "In a double-conversion UPS, the inverter is normally:",
    "choices": [{"id": "A","text": "Bypassed by the static switch and only used during battery discharge"},{"id": "B","text": "Continuously producing AC output power from the DC bus"},{"id": "C","text": "Only active when the utility input voltage is out of tolerance"},{"id": "D","text": "A backup device that replaces the rectifier when input power fails"}],
    "correctAnswerId": "B","explanation": "In a double-conversion (online) UPS, the inverter is always active and continuously produces the AC output voltage.","referenceBookSection": "Inverters — Continuous Operation in Double-Conversion UPS","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 75,"tags": ["inverter","double-conversion","UPS","output"]
  },
  {
    "id": "jr_fse_bypass_001","examLevel": "jr_fse","category": "UPS Components","subcategory": "Static Bypass","difficulty": "medium",
    "questionText": "When a UPS transfers the critical load to static bypass, where does the load now receive its power?",
    "choices": [{"id": "A","text": "From the battery string through the inverter"},{"id": "B","text": "Directly from the utility or bypass source, bypassing the inverter"},{"id": "C","text": "From a secondary UPS connected in parallel"},{"id": "D","text": "From the rectifier output only, without inverter conditioning"}],
    "correctAnswerId": "B","explanation": "When the UPS transfers to static bypass, the critical load is connected directly to the bypass input source.","referenceBookSection": "Static Bypass — Transfer and Source Requirements","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["bypass","static-bypass","transfer","critical-load"]
  },
  {
    "id": "jr_fse_maint_bypass_001","examLevel": "jr_fse","category": "UPS Components","subcategory": "Maintenance Bypass","difficulty": "medium",
    "questionText": "The maintenance bypass switch allows a technician to:",
    "choices": [{"id": "A","text": "Continue operating the UPS inverter while replacing the battery string"},{"id": "B","text": "Connect the critical load to a raw utility path while the UPS is isolated for service"},{"id": "C","text": "Bypass the battery string and run the UPS without battery backup"},{"id": "D","text": "Transfer the UPS to a parallel redundant unit automatically"}],
    "correctAnswerId": "B","explanation": "The maintenance bypass provides a path to connect the critical load directly to the utility while the entire UPS is isolated from the load.","referenceBookSection": "Maintenance Bypass — Purpose and Transfer Sequence","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["maintenance-bypass","isolation","transfer","critical-load"]
  },
  {
    "id": "jr_fse_loto_001","examLevel": "jr_fse","category": "Safety","subcategory": "LOTO Awareness","difficulty": "medium",
    "questionText": "Lockout/Tagout (LOTO) procedures are required when:",
    "choices": [{"id": "A","text": "Replacing a failed external cooling fan only — no electrical energy involved"},{"id": "B","text": "Servicing equipment where unexpected energization or release of stored energy could cause injury"},{"id": "C","text": "Checking external indicator lights on an energized UPS panel"},{"id": "D","text": "Performing visual inspections of battery string labels and rack labeling"}],
    "correctAnswerId": "B","explanation": "LOTO procedures are required when servicing or maintaining equipment where the unexpected energization, startup, or release of stored energy could cause injury.","referenceBookSection": "Safety Concepts — LOTO and Stored Energy","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["LOTO","safety","stored-energy","OSHA"]
  },
  {
    "id": "jr_fse_escalation_001","examLevel": "jr_fse","category": "Field Judgment","subcategory": "Escalation","difficulty": "medium",
    "questionText": "A technician encounters a fault condition on a UPS that is outside the scope of their training or authorization. The correct action is to:",
    "choices": [{"id": "A","text": "Attempt to diagnose the fault using trial and error to avoid downtime"},{"id": "B","text": "Escalate to a more qualified technician, supervisor, or the OEM support line"},{"id": "C","text": "Transfer the load to maintenance bypass and leave the system for the next shift"},{"id": "D","text": "Acknowledge the fault on the UPS panel and continue monitoring"}],
    "correctAnswerId": "B","explanation": "When a fault condition is outside a technician's training or authorization, the correct action is to escalate.","referenceBookSection": "Field Judgment — Escalation and Critical Load Protection","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["escalation","field-judgment","critical-load","safety"]
  },
  {
    "id": "jr_fse_alarm_001","examLevel": "jr_fse","category": "Alarm Recognition","subcategory": "Basic UPS Alarms","difficulty": "medium",
    "questionText": "A UPS displays a 'Battery Discharged' or 'Low Battery' alarm while utility power is present. This most likely indicates:",
    "choices": [{"id": "A","text": "The bypass source is out of tolerance"},{"id": "B","text": "The battery string is depleted and needs charging or replacement review"},{"id": "C","text": "The inverter has failed and is running from battery"},{"id": "D","text": "The UPS input circuit breaker has tripped"}],
    "correctAnswerId": "B","explanation": "A 'Low Battery' alarm while utility power is present indicates the battery string has reached a low state of charge.","referenceBookSection": "Alarms — Reading and Interpreting UPS Alarms","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["alarm","battery","low-battery","UPS"]
  },
  {
    "id": "jr_fse_sts_001","examLevel": "jr_fse","category": "STS Systems","subcategory": "STS Basics","difficulty": "medium",
    "questionText": "A Static Transfer Switch (STS) is primarily used to:",
    "choices": [{"id": "A","text": "Convert AC power to DC power for battery charging"},{"id": "B","text": "Automatically transfer a critical load between two independent power sources with minimal interruption"},{"id": "C","text": "Provide voltage regulation only, without switching capability"},{"id": "D","text": "Replace the UPS inverter when the inverter fails"}],
    "correctAnswerId": "B","explanation": "An STS monitors two independent power sources and can transfer the critical load from a preferred source to an alternate source with minimal interruption.","referenceBookSection": "STS Systems — Purpose and Basic Operation","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["STS","static-transfer-switch","redundancy","transfer"]
  },
  {
    "id": "jr_fse_docs_001","examLevel": "jr_fse","category": "Field Documentation","subcategory": "Service Reporting","difficulty": "easy",
    "questionText": "Why is accurate field documentation important after completing UPS service work?",
    "choices": [{"id": "A","text": "It is only required when the customer requests a written report"},{"id": "B","text": "It creates a record of work performed, conditions found, and actions taken — supporting safety, accountability, and future service"},{"id": "C","text": "It is primarily for billing purposes and has no technical value"},{"id": "D","text": "It is only necessary for major repairs, not for routine inspections"}],
    "correctAnswerId": "B","explanation": "Accurate documentation records what was found, what was done, and what remains, supporting future technicians and compliance.","referenceBookSection": "Field Documentation and Service Reporting","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 75,"tags": ["documentation","service-report","field-service"]
  },
  {
    "id": "jr_fse_amp_clamp_001","examLevel": "jr_fse","category": "Meter Usage","subcategory": "Amp Clamp Basics","difficulty": "medium",
    "questionText": "An amp clamp (clamp meter) measures current by:",
    "choices": [{"id": "A","text": "Being connected in series with the circuit, interrupting current flow through the meter"},{"id": "B","text": "Sensing the magnetic field produced by current flow through a conductor without breaking the circuit"},{"id": "C","text": "Measuring voltage drop across a known internal shunt resistor"},{"id": "D","text": "Clamping across both the hot and neutral conductors simultaneously"}],
    "correctAnswerId": "B","explanation": "An amp clamp senses the magnetic field generated by current flowing through a conductor. No circuit interruption is needed.","referenceBookSection": "Meter Usage — Amp Clamp and Current Measurement","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["amp-clamp","current","measurement","meter"]
  },
  {
    "id": "jr_fse_pdu_001","examLevel": "jr_fse","category": "Power Distribution","subcategory": "PDU and RPP Basics","difficulty": "easy",
    "questionText": "A Power Distribution Unit (PDU) in a data center primarily serves to:",
    "choices": [{"id": "A","text": "Convert high-voltage utility power to battery DC voltage"},{"id": "B","text": "Distribute power from a UPS or other upstream source to multiple downstream loads"},{"id": "C","text": "Provide battery backup for individual server racks"},{"id": "D","text": "Monitor network traffic and power usage simultaneously"}],
    "correctAnswerId": "B","explanation": "A PDU takes power from an upstream source and distributes it to multiple downstream loads through circuit breakers.","referenceBookSection": "PDU / RPP — Distribution Basics","safetyCritical": false,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 60,"tags": ["PDU","RPP","distribution","data-center"]
  },
  {
    "id": "jr_fse_ppe_001","examLevel": "jr_fse","category": "Safety","subcategory": "PPE Awareness","difficulty": "medium",
    "questionText": "Before performing voltage measurements on an energized UPS panel, a technician must verify that their meter and test leads are:",
    "choices": [{"id": "A","text": "Rated for the voltages and categories present in the circuit being tested"},{"id": "B","text": "The most recently purchased model available"},{"id": "C","text": "Approved by the UPS manufacturer for use with that model"},{"id": "D","text": "Pre-tested by another technician earlier that day"}],
    "correctAnswerId": "A","explanation": "Meters and test leads must be rated for the voltages and installation category (CAT II, CAT III, CAT IV) of the circuit being measured.","referenceBookSection": "Meter Usage — Safe Measurement Concepts","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["PPE","meter","CAT-rating","safety"]
  },
  {
    "id": "jr_fse_troubleshoot_001","examLevel": "jr_fse","category": "Troubleshooting","subcategory": "Basic Troubleshooting Sequence","difficulty": "medium",
    "questionText": "A UPS that has recently alarmed and transferred to bypass is still on bypass when you arrive. Before any other action, what is the first priority?",
    "choices": [{"id": "A","text": "Immediately attempt to return the UPS to normal operation to reduce bypass exposure"},{"id": "B","text": "Identify and understand the current system state, the critical load status, and the alarms present before taking any action"},{"id": "C","text": "Call the OEM technical support line and begin a parts order"},{"id": "D","text": "Turn the UPS off and back on to clear the fault"}],
    "correctAnswerId": "B","explanation": "In field service, the first action is always to understand the current state before taking action.","referenceBookSection": "Troubleshooting Logic — Field Reasoning and Safe Sequence","safetyCritical": true,"reviewRequired": false,"active": true,"estimatedTimeSeconds": 90,"tags": ["troubleshooting","field-judgment","critical-load","bypass"]
  }
];

export async function GET(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get('secret');
  if (!SEED_SECRET || secret !== SEED_SECRET) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const clearUid = req.nextUrl.searchParams.get('clearUid');

  try {
    // Seed questions — both Jr FSE and FSE banks
    const allQuestions = [...QUESTIONS, ...FSE_QUESTIONS];
    const batch = adminDb.batch();
    for (const q of allQuestions) {
      const ref = adminDb.collection('questionBank').doc(q.id);
      batch.set(ref, { ...q, updatedAt: FieldValue.serverTimestamp() });
    }
    await batch.commit();

    // Optionally clear cooldown for a specific user
    let cleared = 0;
    if (clearUid) {
      const attSnap = await adminDb.collection('examAttempts').where('userId', '==', clearUid).get();
      const ipSnap = await adminDb.collection('ipExamLocks').where('userId', '==', clearUid).get();
      const b2 = adminDb.batch();
      attSnap.docs.forEach((d) => b2.delete(d.ref));
      ipSnap.docs.forEach((d) => b2.delete(d.ref));
      await b2.commit();
      cleared = attSnap.size + ipSnap.size;
    }

    return NextResponse.json({ success: true, count: allQuestions.length, jr_fse: QUESTIONS.length, fse: FSE_QUESTIONS.length, cleared });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
