import { NextRequest, NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';
import { adminAuth, adminDb } from '@/lib/firebase/admin';
import { checkIsAdmin } from '@/lib/utils/isAdmin';
import { FieldValue } from 'firebase-admin/firestore';

export const dynamic = 'force-dynamic';
export const maxDuration = 300;

// JSON files are read from disk at request time via fs.readFileSync.
// next.config.js outputFileTracingIncludes ensures data/questions/** is
// deployed alongside the function. Nothing is webpack-bundled — cold start
// is minimal (just firebase-admin + a few KB of route logic).

type QuestionRecord = Record<string, unknown>;

// Fresh JSON files use their exact filename (with .json).
// Derived bank keys have no extension — the file on disk is `${key}.json`,
// pre-generated by scripts/gen-derived-banks.ts.
// All files live in data/questions/ and are included via outputFileTracingIncludes.
// Zero dynamic imports — cold start is just firebase-admin + this tiny module.

const FRESH_FILES = new Set([
  'jr-fsc-sample.json',
  'jr-fse-all-questions.json',
  'book-jr-fse-questions.json',
  'fsc-sample.json',
  'book-fse-questions.json',
  'kitchen-jr-fse-fresh.json',
  'hvac-jr-fse-fresh.json',
  'generator-jr-fse-fresh.json',
  'datacenter-jr-fresh.json',
  'solar-jr-fresh.json',
  'ev-jr-fresh.json',
  'dcp-jr-fresh.json',
  'battery-jr-fresh.json',
  'dc-engineer-jr-fresh.json',
  'marine-jr-fresh.json',
  'pool-jr-fresh.json',
  'hvac-tech-jr-fresh.json',
  'solar-installer-jr-fresh.json',
  'wind-turbine-jr-fresh.json',
  'elevator-tech-jr-fresh.json',
  'fire-alarm-tech-jr-fresh.json',
  'bmet-tech-jr-fresh.json',
  'bas-tech-jr-fresh.json',
  'ref-tech-jr-fresh.json',
  'plc-tech-jr-fresh.json',
  'security-tech-jr-fresh.json',
  'field-pm-jr-fresh.json',
  'pump-tech-jr-fresh.json',
]);

const DERIVED_BANKS = new Set([
  'kitchen-jr-fse-derived',
  'hvac-jr-fse-derived',
  'generator-jr-fse-derived',
  'datacenter-jr-derived',
  'solar-jr-derived',
  'ev-jr-derived',
  'dcp-jr-derived',
  'battery-jr-derived',
  'dc-engineer-jr-derived',
  'marine-jr-derived',
  'pool-jr-derived',
  'hvac-tech-jr-derived',
  'solar-installer-jr-derived',
  'wind-turbine-jr-derived',
  'elevator-tech-jr-derived',
  'fire-alarm-tech-jr-derived',
  'bmet-tech-jr-derived',
  'bas-tech-jr-derived',
  'ref-tech-jr-derived',
  'plc-tech-jr-derived',
  'security-tech-jr-derived',
  'field-pm-jr-derived',
  'pump-tech-jr-derived',
]);

function getFileQuestions(name: string): QuestionRecord[] | null {
  const qDir = join(process.cwd(), 'data', 'questions');
  try {
    if (FRESH_FILES.has(name)) {
      return JSON.parse(readFileSync(join(qDir, name), 'utf-8')) as QuestionRecord[];
    }
    if (DERIVED_BANKS.has(name)) {
      return JSON.parse(readFileSync(join(qDir, `${name}.json`), 'utf-8')) as QuestionRecord[];
    }
  } catch {
    return null;
  }
  return null;
}

const FILE_ORDER = [
  'jr-fsc-sample.json',
  'jr-fse-all-questions.json',
  'book-jr-fse-questions.json',
  'fsc-sample.json',
  'book-fse-questions.json',
  'kitchen-jr-fse-fresh.json',
  'kitchen-jr-fse-derived',
  'hvac-jr-fse-fresh.json',
  'hvac-jr-fse-derived',
  'generator-jr-fse-fresh.json',
  'generator-jr-fse-derived',
  'datacenter-jr-fresh.json',
  'datacenter-jr-derived',
  'solar-jr-fresh.json',
  'solar-jr-derived',
  'ev-jr-fresh.json',
  'ev-jr-derived',
  'dcp-jr-fresh.json',
  'dcp-jr-derived',
  'battery-jr-fresh.json',
  'battery-jr-derived',
  'dc-engineer-jr-fresh.json',
  'dc-engineer-jr-derived',
  'marine-jr-fresh.json',
  'marine-jr-derived',
  'pool-jr-fresh.json',
  'pool-jr-derived',
  'hvac-tech-jr-fresh.json',
  'hvac-tech-jr-derived',
  'solar-installer-jr-fresh.json',
  'solar-installer-jr-derived',
  'wind-turbine-jr-fresh.json',
  'wind-turbine-jr-derived',
  'elevator-tech-jr-fresh.json',
  'elevator-tech-jr-derived',
  'fire-alarm-tech-jr-fresh.json',
  'fire-alarm-tech-jr-derived',
  'bmet-tech-jr-fresh.json',
  'bmet-tech-jr-derived',
  'bas-tech-jr-fresh.json',
  'bas-tech-jr-derived',
  'ref-tech-jr-fresh.json',
  'ref-tech-jr-derived',
  'plc-tech-jr-fresh.json',
  'plc-tech-jr-derived',
  'security-tech-jr-fresh.json',
  'security-tech-jr-derived',
  'field-pm-jr-fresh.json',
  'field-pm-jr-derived',
  'pump-tech-jr-fresh.json',
  'pump-tech-jr-derived',
];

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get('Authorization');
    const idToken = authHeader?.split('Bearer ')[1];
    if (!idToken) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const decoded = await adminAuth.verifyIdToken(idToken);
    if (!(await checkIsAdmin(decoded.uid, decoded.email ?? ''))) {
      return NextResponse.json({ error: 'Forbidden — admin only' }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const fileName = body.file as string | undefined;
    const filesToImport = fileName ? [fileName] : FILE_ORDER;

    const collection = adminDb.collection('questionBank');
    let totalCreated = 0;
    const filesProcessed: string[] = [];
    const filesNotFound: string[] = [];

    const BATCH_SIZE = 500;
    // 50-second per-file deadline covering BOTH module loading and Firestore writes.
    // Derived banks load kitchenBank dynamically; if that takes too long the server
    // returns a 500 and the client marks the file as timed-out and moves on.
    const PER_FILE_MS = 50_000;

    for (const file of filesToImport) {
      try {
        await Promise.race([
          (async () => {
            const questions = await getFileQuestions(file);
            if (!questions || questions.length === 0) {
              filesNotFound.push(file);
              return;
            }
            const batches: ReturnType<typeof adminDb.batch>[] = [];
            let count = 0;
            for (let i = 0; i < questions.length; i += BATCH_SIZE) {
              const chunk = questions.slice(i, i + BATCH_SIZE);
              const batch = adminDb.batch();
              for (const q of chunk) {
                const id = q.id as string;
                if (!id) continue;
                batch.set(
                  collection.doc(id),
                  { ...q, updatedAt: FieldValue.serverTimestamp() },
                  { merge: true }
                );
                count++;
              }
              batches.push(batch);
            }
            await Promise.all(batches.map((b) => b.commit()));
            totalCreated += count;
            filesProcessed.push(`${file} (${questions.length})`);
          })(),
          new Promise<never>((_, rej) =>
            setTimeout(() => rej(new Error(`server timeout after 50s`)), PER_FILE_MS)
          ),
        ]);
      } catch (fileErr: any) {
        filesNotFound.push(`${file} (${fileErr.message})`);
      }
    }

    await adminDb.collection('auditLogs').add({
      userId: decoded.uid,
      eventType: 'bulk_questions_imported_from_server',
      eventDetails: { filesProcessed, filesNotFound, totalCreated },
      createdAt: FieldValue.serverTimestamp(),
      severity: 'info',
    });

    return NextResponse.json({ ok: true, filesProcessed, filesNotFound, totalCreated, totalUpdated: 0 });
  } catch (err: any) {
    console.error('Import from server error:', err);
    return NextResponse.json({ error: err.message ?? 'Import failed' }, { status: 500 });
  }
}
